pipeline {
    agent any

    environment {
        packageVersion = ''
    }

    stages {
        stage('Get version') {
            steps {
                script {
                    def packageJson = readJSON(file: 'package.json')
                    packageVersion = packageJson.version
                    echo "version: ${packageVersion}"
                }
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Unit test') {
            steps {
                echo "unit testing is done here"
            }
        }

        stage('Sonar Scan') {
            environment {
                SCANNER_HOME = tool 'sonar-6.0'
            }
            steps {
                withSonarQubeEnv('sonar-6.0') {
                    sh "${SCANNER_HOME}/bin/sonar-scanner"
                }
            }
        }

        stage('SQuality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker build') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account_id}.dkr.ecr.us-east-1.amazonaws.com
                        docker build -t ${account_id}.dkr.ecr.us-east-1.amazonaws.com/${project}/${environment}/${component}:${appVersion} .
                    """
                }
            }
        }

        stage('Deploy') {
            when {
                expression { params.deploy }
            }
            steps {
                build job: 'backend-cd', parameters: [
                    string(name: 'version', value: "${appVersion}"),
                    string(name: 'ENVIRONMENT', value: "dev")
                ], wait: true
            }
        }
    }

    post {
        always {
            echo "========always========"
            deleteDir()
        }
        success {
            echo "========Pipeline executed successfully========"
        }
        failure {
            echo "========Pipeline execution failed========"
        }
    }
}